---
toc: false
---

# Introduction {#sec-monitoring-ias}

Belgium is legally obligated to monitor invasive alien species (IAS) on the List of Invasive Alien Species of Union Concern (Union List in short) under the EU Invasive Alien Species Regulation [@noauthor_regulation_2014]..
For the Flemish region, the coordination of such monitoring is a statutory task of the Institute for Nature and Forest (INBO). However, despite this obligation, Flanders currently still lacks a dedicated and coherent monitoring programme that systematically covers all Union List species.

Instead, a considerable number of independent monitoring and early alert initiatives exist, forming a rather heterogeneous mix (ref: Belgium’s EU reporting). Some initiatives are species- or taxon-focused and operate across the entire Flemish region, such as Vespawatch (ref), Flatwormwatch (ref), and Craywatch (ref), which are also largely citizen science-based. Others, such as LIFE 3nBullfrog (ref), LIFE DUNIAS (ref), LIFE RIPARIAS (ref), and Interreg MICA (ref), also focus on particular taxa but are geographically restricted to specific regions or ecosystems and often involve a mix of professional and citizen-based monitoring. These initiatives are typically project-based, not structurally funded, and therefore time-limited unless explicitly extended. In addition, a large amount of IAS data is collected opportunistically through biodiversity reporting platforms like waarnemingen.be (ref), which - although not designed for IAS specifically - capture many relevant records thanks to their widespread use. Lastly, some IAS are recorded incidentally in professional monitoring schemes targeting native species (ref: Maes et al.).

This fragmented and largely uncoordinated situation highlights the need for a more structured and strategic approach to IAS monitoring in Flanders. A future IAS monitoring programme should aim to better integrate these existing efforts—both citizen science and professional monitoring—while filling gaps through the development of new, targeted monitoring schemes. Ideally, such a programme would draw on a methodological framework to closely align monitoring targets, data collection, data analysis and reporting with policy needs, ensuring reliable, robust, and policy-relevant insights.Promoting such a framework, INBO has developed extensive guidelines for designing policy-oriented monitoring schemes [@wouters_ontwerp_2008-1].
The guidelines have successfully been applied, for instance in response to the EU Habitat Directive (ref) where they underlie the corresponding species monitoring schemes (ref soortenmeetnetten).

The endeavor documented in the current report aims to lay the groundwork for future applications of the INBO monitoring guidelines to plan structured monitoring schemes for IAS in Flanders. As a first step, we designed and conducted an expert survey to collect targeted information on IAS in the Flemish region. This concerns the species’ invasion stage - including their present and expected introduction, distribution, abundance, and impacts; their assessment via existing monitoring schemes and opportunistic data; the quality, costs, and feasibility of available monitoring techniques; and whether the species are currently subject to management actions. The survey results were then used in a prioritization process to identify a limited number of species for which monitoring schemes should be developed with priority. The survey project was concluded with a meeting of a steering committee involving external stakeholders from the Agency for Nature and Forest (ANB) and the Flanders Environment Agency (VMM) who evaluated the project’s results and took the final decision on which species or species groups should be prioritized for the future development of monitoring schemes.

The remainder of this report is structured as follows: The design of the expert survey and the employed prioritization methodology are described in detail in @sec-survey-design. The survey results are presented in @sec-survey-results including [insert brief summary results section]. A brief summary of the steering committee meeting and decision is provided in @sec-committee.
Before proceeding however, we first provide some relevant background information. In the (ref section), we briefly summarize the relevant legislation on IAS monitoring in Flanders, including provisions at both the EU and Flemish levels. This is followed by a note on terminology, clarifying differences between how terms are used in legislative texts and how they are applied in this report. We then introduce a distinction between different types of monitoring scopes - referring to specific objectives and designs of monitoring schemes depending on the species’ invasion stage and management context. For example, some scopes aim at early detection of species not yet present in Flanders, while others focus on assessing trends in abundance or evaluating control measures for already widespread species. This distinction of different monitoring scopes will be used throughout the report to help structure and interpret the survey results.
