function sendEmail() {

MailApp.sendEmail('janne.adolf@posteo.de', 'Bevraging invasieve soorten', 'Beste Janne Adolf,\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod leo justo, sed rutrum magna ornare ut. Praesent non consequat tellus. Sed sodales tellus non dignissim condimentum. Aliquam sed nisl quis leo bibendum dignissim ut sit amet mi. Ut quis consectetur eros. Duis semper molestie maximus. Sed tempus iaculis quam in gravida. Morbi eleifend diam eu nisi accumsan rhoncus. Etiam consequat enim id ipsum varius molestie. Vivamus sit amet nunc augue.\n\nInteger dictum odio placerat tempus cursus. Nunc vitae neque vehicula, convallis mi a, tristique enim. Nulla sed ante dictum, luctus risus non, volutpat diam. Fusce egestas diam vitae hendrerit facilisis. Sed placerat mollis orci. Sed accumsan fermentum odio, quis laoreet est sodales sed. Duis sed neque rhoncus mi luctus sollicitudin. Fusce euismod accumsan libero, nec varius velit dignissim at. Sed elementum suscipit arcu vel sodales.\n\nLink naar de bevraging:\nhttps://docs.google.com/forms/d/e/1FAIpQLSePRrrICh4YdRKHu_QYXEFenRgFYf8PSbJ_2uG_vgMKcpW-lQ/viewform\n\nBedankt voor uw hulp.\n\nMet vriendelijke groet,\nJanne Adolf\n');

MailApp.sendEmail('janne.adolf@posteo.de', 'Bevraging invasieve soorten', 'Beste Janne Adolf,\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod leo justo, sed rutrum magna ornare ut. Praesent non consequat tellus. Sed sodales tellus non dignissim condimentum. Aliquam sed nisl quis leo bibendum dignissim ut sit amet mi. Ut quis consectetur eros. Duis semper molestie maximus. Sed tempus iaculis quam in gravida. Morbi eleifend diam eu nisi accumsan rhoncus. Etiam consequat enim id ipsum varius molestie. Vivamus sit amet nunc augue.\n\nInteger dictum odio placerat tempus cursus. Nunc vitae neque vehicula, convallis mi a, tristique enim. Nulla sed ante dictum, luctus risus non, volutpat diam. Fusce egestas diam vitae hendrerit facilisis. Sed placerat mollis orci. Sed accumsan fermentum odio, quis laoreet est sodales sed. Duis sed neque rhoncus mi luctus sollicitudin. Fusce euismod accumsan libero, nec varius velit dignissim at. Sed elementum suscipit arcu vel sodales.\n\nLink naar de bevraging:\nhttps://docs.google.com/forms/d/e/1FAIpQLScOLbgzRMUAsfeWS-s2y_M4pD1OqFdf1Eymql18d1PUkwAMNQ/viewform\n\nBedankt voor uw hulp.\n\nMet vriendelijke groet,\nJanne Adolf\n');

MailApp.sendEmail('janne.adolf@inbo.be', 'Bevraging invasieve soorten', 'Beste Janne,\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod leo justo, sed rutrum magna ornare ut. Praesent non consequat tellus. Sed sodales tellus non dignissim condimentum. Aliquam sed nisl quis leo bibendum dignissim ut sit amet mi. Ut quis consectetur eros. Duis semper molestie maximus. Sed tempus iaculis quam in gravida. Morbi eleifend diam eu nisi accumsan rhoncus. Etiam consequat enim id ipsum varius molestie. Vivamus sit amet nunc augue.\n\nInteger dictum odio placerat tempus cursus. Nunc vitae neque vehicula, convallis mi a, tristique enim. Nulla sed ante dictum, luctus risus non, volutpat diam. Fusce egestas diam vitae hendrerit facilisis. Sed placerat mollis orci. Sed accumsan fermentum odio, quis laoreet est sodales sed. Duis sed neque rhoncus mi luctus sollicitudin. Fusce euismod accumsan libero, nec varius velit dignissim at. Sed elementum suscipit arcu vel sodales.\n\nLink naar de bevraging:\nhttps://docs.google.com/forms/d/e/1FAIpQLScCkbcfwv6X7Y23MnCWEGWK6iBGjtIl_Zjl5e-UR2pqJB76eg/viewform\n\nBedankt voor jouw hulp.\n\nMet vriendelijke groet,\nJanne\n');

MailApp.sendEmail('janne.adolf@posteo.de', 'Bevraging invasieve soorten', 'Beste Janne Adolf,\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam euismod leo justo, sed rutrum magna ornare ut. Praesent non consequat tellus. Sed sodales tellus non dignissim condimentum. Aliquam sed nisl quis leo bibendum dignissim ut sit amet mi. Ut quis consectetur eros. Duis semper molestie maximus. Sed tempus iaculis quam in gravida. Morbi eleifend diam eu nisi accumsan rhoncus. Etiam consequat enim id ipsum varius molestie. Vivamus sit amet nunc augue.\n\nInteger dictum odio placerat tempus cursus. Nunc vitae neque vehicula, convallis mi a, tristique enim. Nulla sed ante dictum, luctus risus non, volutpat diam. Fusce egestas diam vitae hendrerit facilisis. Sed placerat mollis orci. Sed accumsan fermentum odio, quis laoreet est sodales sed. Duis sed neque rhoncus mi luctus sollicitudin. Fusce euismod accumsan libero, nec varius velit dignissim at. Sed elementum suscipit arcu vel sodales.\n\nLink naar de bevraging:\nhttps://docs.google.com/forms/d/e/1FAIpQLSf_8LtpwK3Ikely_danuLWwcnZWhq1I2HrxBpRxwULTXRgTag/viewform\n\nBedankt voor uw hulp.\n\nMet vriendelijke groet,\nJanne Adolf\n');

}

